# -*- coding: utf-8 -*-
"""
/***************************************************************************
 RoteListePflanzenTabelle
                                 A QGIS plugin
 Erstellt .docx Dokument mit einer Tabelle der rote Liste Pflanzen.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-10-23
        copyright            : (C) 2022 by Till Frankenbach
        email                : Tillfrankenbach@web.de
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load RoteListePflanzenTabelle class from file RoteListePflanzenTabelle.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .rote_liste_pflanzen_tabelle import RoteListePflanzenTabelle
    return RoteListePflanzenTabelle(iface)
