# -*- coding: utf-8 -*-
"""
/***************************************************************************
 RedListFaunaTable
                                 A QGIS plugin
 Erstellt docx Tabellen über Fauna.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-12-15
        copyright            : (C) 2023 by Till Frankenbach
        email                : till.frankenbach@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load RedListFaunaTable class from file RedListFaunaTable.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .red_list_fauna_table import RedListFaunaTable

    return RedListFaunaTable(iface)
